name: Documentation CI

on:
  workflow_call:
    inputs:
      git_tag:
        type: string
        description: The git tag (version) from the calling workflow
        required: false

  workflow_dispatch:
    inputs:
      git_tag:
        type: string
        description: The git tag (version) to use for `$TAG`
        required: false

jobs:
  docs-ci:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      TAG: ${{ inputs.git_tag }}
      REF_NAME: ${{ github.ref_name }}
      REF_TYPE: ${{ github.ref_type }}
      REF_HEAD: ${{ github.head_ref }}
      PR_NUMBER: ${{ github.event.number }}  
      PR_TITLE_PREFIX: "task: update documentation for"
      COMMIT_SUFFIX: ${{ inputs.git_tag }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/network-operator-docs  # repo must be explicitly set here for workflow calling to behave correctly
        token: ${{ inputs.token || secrets.GH_TOKEN_NVIDIA_CI_CD }}  # token must be explicitly set here for push to work in following step
    - name: Setup Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: 1.23.x
    - name: Make docs
      run: |
        if [[ -n $PR_NUMBER ]]; then
          export BRANCH=$REF_HEAD
          echo "REF_NAME=$REF_HEAD" >> $GITHUB_ENV
          echo "COMMIT_SUFFIX=pull/$PR_NUMBER" >> $GITHUB_ENV
        else
          export TAG=$REF_NAME
        fi

        #git pull
        #git checkout test-netops-docs-workflow      
        make api-docs helm-docs generate-docs-versions-var
    - name: Close any existing documentation PRs
      run: |
        for pr_number in $(gh pr list --search "$PR_TITLE_PREFIX" --json number --jq ".[].number"); do
          gh pr close $pr_number
        done
    - name: Create PR
      env:
        REF_NAME: ${{ github.ref_name }}
        DOWNSTREAM_REPO_OWNER: heyvister1
        DOWNSTREAM_FEATURE_BRANCH: update-docs-for-${{ env.REF_NAME }}
        UPSTREAM_REPO_OWNER: heyvister1
        UPSTREAM_DEFAULT_BRANCH: main
      run: |
        git config user.name  heyvister1
        git config user.email iheyvi@nvidia.com
      
        #gh repo fork --remote --default-branch-only
        gh repo sync $DOWNSTREAM_REPO_OWNER/network-operator-docs --source $UPSTREAM_REPO_OWNER/network-operator-docs --branch $UPSTREAM_DEFAULT_BRANCH
        
        #git pull
        #git checkout test-netops-docs-workflow
        git checkout -b $DOWNSTREAM_FEATURE_BRANCH
        git add docs
        COMMIT_MESSAGE="$PR_TITLE_PREFIX $COMMIT_SUFFIX"
        git commit -m "$COMMIT_MESSAGE"

        git push -u origin $DOWNSTREAM_FEATURE_BRANCH --force
        gh pr create \
          --head $DOWNSTREAM_REPO_OWNER:$DOWNSTREAM_FEATURE_BRANCH \
          --base $UPSTREAM_DEFAULT_BRANCH \
          --title "$COMMIT_MESSAGE" \
          --body "Created by the *${{ github.job }}* job in [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
